Feature/ex 4 crud reservation
barneystallone/er-nest-topic pull request #1
Opened 2024-01-01 18:00 UTC by barneystallone

## **Summary:**

- Integrated Mysql
- Implement CRUD functions for the reservation feature

**Changes:**
---
-  Could you please check if the source code is functioning? Installation instructions are available at the following [LINK](https://github.com/barneystallone/er-nest-topic/blob/feature/EX-4-crud_reservation/README.md) 
- Migrate entities into the database
- Dockerize the application
-  Add some decorators to validate the data 
   1. Not empty,  check if it is the valid date format
   2. The end date must be after the start date
   3. The start date must be before now
- Next, I will do the user and JWT parts and will update this reservation feature later. 

## **Checked List**
---
**Create 1 reservation**
![image](https://github.com/barneystallone/er-nest-topic/assets/84855261/4e5226c5-c520-4e2f-89c9-dc04aa07c0fa)
---

**Get all reservations**
![image](https://github.com/barneystallone/er-nest-topic/assets/84855261/e28288b9-c7b9-49de-80ff-2e747e39b265)
--

**Get 1 reservation by ID**
![image](https://github.com/barneystallone/er-nest-topic/assets/84855261/3a34103a-e361-480e-8e63-23c319939833)
--

**Update/Create 1 reservation: Case `start_date > end_date`**
![image](https://github.com/barneystallone/er-nest-topic/assets/84855261/e9a5e13c-2746-4d9a-a2f0-2b8f65665748)
---

**Update/Create 1 reservation: Case `start_date < now()`**
![image](https://github.com/barneystallone/er-nest-topic/assets/84855261/c451498a-414a-4553-bbbb-91bb6643c0a2)
---

**Delete 1 reservation**
![image](https://github.com/barneystallone/er-nest-topic/assets/84855261/c84d0a7a-7c2b-49d7-86fa-d090ab8d1e82)

## **Other:**
- Using MikroORM to persist data 
- Using class-transformer, and class-validator, joi  to validate, transform data and payload (dto)
- Using date-fns for  Date Manipulation 
- Using uuid for generate id

## **References**
- API Specification : [LINK](https://docs.google.com/spreadsheets/d/1E00EAiQ_OvmwJDmjUwNJaruzasgwLeurWhjmqICXxSg)
- Backlog : [Ticket EX-4](https://docs.google.com/spreadsheets/d/1E00EAiQ_OvmwJDmjUwNJaruzasgwLeurWhjmqICXxSg)

2024-01-02 06:36 UTC, er-vuldh requested changes

2024-01-02 06:36 UTC, er-vuldh commented on src/common/helpers/success.response.ts
File name chưa thống nhất, nên có đuôi là helper.ts

2024-01-02 06:36 UTC, er-vuldh commented on src/reservations/reservations.module.ts
Reservations là module business, nếu gom vào sub folder modules thì sẽ gọn hơn, ở top folder này thì nên có nhưng common module hoặc là config là ok rồi

2024-01-02 06:36 UTC, er-vuldh commented on src/reservations/dto/create-reservation.dto.ts
> +export class CreateReservationDto {
Nên có 1 empty line giữa import và content của class, không nên viết liền lại như vậy

2024-01-02 06:48 UTC, er-vuldh commented
@barneystallone 
<img width="1330" alt="Screenshot 2024-01-02 at 13 46 51" src="https://github.com/barneystallone/er-nest-topic/assets/118418412/8ad9d433-7dc8-4c93-820e-48297101e59c">
Thêm cái nữa, nhớ squash thành 1 commit rồi mới tạo PR nhé, không nên tạo nhiều commit trong 1 PR, chỗ này có nói ở bài GIT rồi

2024-01-02 06:54 UTC, barneystallone commented on src/common/helpers/success.response.ts
Đoạn này sau này em định tách ra với là common/response là success.response.ts và sau này sẽ là error.response.ts, xong rồi sót phần này :cry:

2024-01-03 01:52 UTC, er-vuldh commented on src/common/types/enums/response.enum.ts
> +  CREATED = 'CREATED',
Nên thống nhất content chữ hoa thường, next time consider cho i18n hoặc multi lang

2024-01-03 12:20 UTC, merged