[EX-32] Send email
barneystallone/er-nest-topic pull request #4
Opened 2024-01-06 00:56 UTC by barneystallone

**Summary**
- Implement  email-sending feature 
- Retry up to a maximum of 5 times if sending fails

**Changes**
- Add nodemailer library to be able to send emails

**Checked list**
[Email Sending Feature Demo ](https://github.com/barneystallone/er-nest-topic/assets/84855261/63b5c8dd-8fce-41a2-a50f-934759456d6e)

**Other**
- N/A

**References**
- N/A

2024-01-13 03:11 UTC, er-vuldh requested changes

2024-01-13 03:11 UTC, er-vuldh commented on src/app.controller.ts
> +  // @Get('test-email')
code k dùng nữa xoá đi nhé

2024-01-13 03:11 UTC, er-vuldh commented on src/app.controller.ts
>    @Get('test-i18n')
này cũng thừa đúng k

2024-01-13 03:11 UTC, er-vuldh commented on src/resources/i18n/en/email.json
> +{
template nên dùng file html hoặc template engine, localization nên call được hàm translate trong template. để dùng chung 1 layout, nếu như vậy thì sửa layout phải sửa ở tất cả lang

2024-01-13 13:56 UTC, barneystallone commented on src/app.controller.ts
>    @Get('test-i18n')
Dạ em xin lỗi vì quên xóa ạ, tại PR này em làm branch khác với lại làm lâu quá nên quên ạ

2024-01-13 13:59 UTC, barneystallone commented on src/resources/i18n/en/email.json
> +{
Dạ đúng rồi, em chưa nghĩ đến vấn đề này

2024-01-15 06:37 UTC, er-vuldh approved these changes
OK rồi

2024-01-18 00:24 UTC, merged