[EX-5] Impl logger module and mask sensitive data
barneystallone/er-nest-topic pull request #6
Opened 2024-01-07 04:03 UTC by barneystallone

**Summary**
- Request / Response Log
- Error Log (50% complete; update after finishing the error handling module)
- Mask Sensitive Data (string, array, object, nested array, nested object)

**Changes**
- I added a `resource/sensitive-keyword.json` file to store the keywords that need to be masked 
- I have organized the log files based on date and log level.
- I am currently a bit uncertain about what to write or how to structure the folders since the documentation doesn't provide much information on this matter.

**Checked List**
![Screenshot from 2024-01-07 10-41-52](https://github.com/barneystallone/er-nest-topic/assets/84855261/0c4f72cb-c1c5-4aa1-a638-cb47f48bc532)
![image](https://github.com/barneystallone/er-nest-topic/assets/84855261/39492aea-2da5-498a-86ca-6f9821cadb47)

**Other**
- N/A

**References**
- N/A

2024-01-08 02:09 UTC, er-vuldh requested changes

2024-01-08 02:09 UTC, er-vuldh commented on src/common/decorators/isAfterNow.ts
>      return +new Date(dateStr) > +new Date();
toán tử + nếu cần nên thêm ngoặc và để tránh người khác xoá nhầm

2024-01-08 02:09 UTC, er-vuldh commented on src/common/helpers/data-masking.helper.ts
> +// logger.verbose(
xoá comment

2024-01-08 02:09 UTC, er-vuldh commented on src/common/interceptors/logger.interceptor.ts
> +        this.writeToLogFile(LOG_PATH.REQUEST, logMessage);
Nên dùng winston và route log qua winton để xử lý, sử dụng log filter và các feature của winston để tránh làm các việc thừa

2024-01-08 02:09 UTC, er-vuldh commented on src/common/interceptors/logger.interceptor.ts
> +        `\n\n[${timestamp}][${LOG_LEVEL.ERROR}][${loggerName}] ${method} ${url} - ${responseTime}\n\n` +
winston có hỗ trợ log format

2024-01-08 02:09 UTC, er-vuldh commented on src/common/types/enums/logging.enum.ts
> +  DEBUG = 'DEBUG',
winston đã có k cần làm thêm

2024-01-08 02:13 UTC, barneystallone commented on src/common/types/enums/logging.enum.ts
> +  DEBUG = 'DEBUG',
Dạ em hiểu rồi

2024-01-08 02:17 UTC, barneystallone commented on src/common/types/enums/logging.enum.ts
> +  DEBUG = 'DEBUG',
Để em tìm hiểu rồi làm với winston ạ

2024-01-11 01:53 UTC, er-vuldh commented
@barneystallone 
Log khi ghi vào file nên ghi theo line và có format rõ ràng, 

Ví dụ log request, response thường sẽ có ít nhất là, datetime, log level, class, message.
ngoài ra còn có thêm các thông tin extra như requestId,...

Còn về log error thì như trên nhưng có thêm phần error tracing.

ngoài ra còn phải có 1 loại nữa là application log, loại này format cũng tương tự nhưng phần message sẽ do từng usercase mà dev muốn

![image](https://github.com/barneystallone/er-nest-topic/assets/118418412/73a5b50d-5639-40cc-b775-f8929c6a73aa)

2024-01-11 08:34 UTC, er-vuldh approved these changes

2024-01-16 13:27 UTC, merged